<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-H79G770" failures="2" tests="8" name="Default test(failed)" time="0.177" errors="0" timestamp="2024-06-18T14:52:19 IST">
  <testcase classname="batch.FailureTestCase" name="t1" time="0.02">
    <skipped/>
  </testcase> <!-- t1 -->
  <testcase classname="batch.FailureTestCase" name="t1" time="0.005">
    <skipped/>
  </testcase> <!-- t1 -->
  <testcase classname="batch.FailureTestCase" name="t1" time="0.005">
    <skipped/>
  </testcase> <!-- t1 -->
  <testcase classname="batch.FailureTestCase" name="t1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at batch.FailureTestCase.t1(FailureTestCase.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- t1 -->
  <testcase classname="batch.FailureTestCase" name="t3" time="0.002">
    <skipped/>
  </testcase> <!-- t3 -->
  <testcase classname="batch.FailureTestCase" name="t3" time="0.003">
    <skipped/>
  </testcase> <!-- t3 -->
  <testcase classname="batch.FailureTestCase" name="t3" time="0.003">
    <skipped/>
  </testcase> <!-- t3 -->
  <testcase classname="batch.FailureTestCase" name="t3" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at batch.FailureTestCase.t3(FailureTestCase.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- t3 -->
  <testcase classname="batch.FailureTestCase" name="t2" time="0.0">
    <ignored/>
  </testcase> <!-- t2 -->
</testsuite> <!-- Default test(failed) -->
